language: java

# Setting sudo to false will cause Travis to use Containers.
# To use Docker's privileged mode, we need to enable sudo.
sudo: required

#services:
#  - docker

jdk:
  - openjdk9
  - openjdk10

before_script: ./tools/version.sh verify

script: mvn package
