language: java

# Setting sudo to false will cause Travis to use Containers.
# To use Docker's privileged mode, we need to enable sudo.
sudo: required

jdk:
  -oraclejdk8
  -openjdk8

before_script: ./tools/version.sh verify

script: mvn package
